// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestDto.proto

package com.xk.nettydemo.bean;

public final class TestDtoModel {
    private TestDtoModel()
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry)
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry)
    {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TestDtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TestDto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool boolean = 1;</code>
         */
        boolean getBoolean();

        /**
         * <code>double doub = 2;</code>
         */
        double getDoub();

        /**
         * <code>int32 id = 3;</code>
         */
        int getId();

        /**
         * <code>string name = 4;</code>
         */
        String getName();

        /**
         * <code>string name = 4;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>bytes b = 5;</code>
         */
        com.google.protobuf.ByteString getB();

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        java.util.List<TestDto.PhoneNumber>
        getPhonesList();

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        TestDtoModel.TestDto.PhoneNumber getPhones(int index);

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        int getPhonesCount();

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        java.util.List<? extends TestDto.PhoneNumberOrBuilder>
        getPhonesOrBuilderList();

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        TestDtoModel.TestDto.PhoneNumberOrBuilder getPhonesOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code TestDto}
     */
    public static final class TestDto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:TestDto)
            TestDtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use TestDto.newBuilder() to construct.
        private TestDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
        {
            super(builder);
        }

        private TestDto()
        {
            boolean_ = false;
            doub_ = 0D;
            id_ = 0;
            name_ = "";
            b_ = com.google.protobuf.ByteString.EMPTY;
            phones_ = java.util.Collections.emptyList();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields()
        {
            return this.unknownFields;
        }

        private TestDto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            boolean_ = input.readBool();
                            break;
                        }
                        case 17: {

                            doub_ = input.readDouble();
                            break;
                        }
                        case 24: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 42: {

                            b_ = input.readBytes();
                            break;
                        }
                        case 50: {
                            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                                phones_ = new java.util.ArrayList<PhoneNumber>();
                                mutable_bitField0_ |= 0x00000020;
                            }
                            phones_.add(
                                    input.readMessage(TestDtoModel.TestDto.PhoneNumber.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                    phones_ = java.util.Collections.unmodifiableList(phones_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return TestDtoModel.internal_static_TestDto_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return TestDtoModel.internal_static_TestDto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestDtoModel.TestDto.class, TestDtoModel.TestDto.Builder.class);
        }

        /**
         * Protobuf enum {@code TestDto.PhoneType}
         */
        public enum PhoneType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>MOBILE = 0;</code>
             */
            MOBILE(0),
            /**
             * <code>HOME = 1;</code>
             */
            HOME(1),
            /**
             * <code>WORK = 2;</code>
             */
            WORK(2),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>MOBILE = 0;</code>
             */
            public static final int MOBILE_VALUE = 0;
            /**
             * <code>HOME = 1;</code>
             */
            public static final int HOME_VALUE = 1;
            /**
             * <code>WORK = 2;</code>
             */
            public static final int WORK_VALUE = 2;


            public final int getNumber()
            {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static PhoneType valueOf(int value)
            {
                return forNumber(value);
            }

            public static PhoneType forNumber(int value)
            {
                switch (value) {
                    case 0:
                        return MOBILE;
                    case 1:
                        return HOME;
                    case 2:
                        return WORK;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap()
            {
                return internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<
                    PhoneType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                        public PhoneType findValueByNumber(int number)
                        {
                            return PhoneType.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor()
            {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType()
            {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor()
            {
                return TestDtoModel.TestDto.getDescriptor().getEnumTypes().get(0);
            }

            private static final PhoneType[] VALUES = values();

            public static PhoneType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc)
            {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private PhoneType(int value)
            {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:TestDto.PhoneType)
        }

        public interface PhoneNumberOrBuilder extends
                // @@protoc_insertion_point(interface_extends:TestDto.PhoneNumber)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string number = 1;</code>
             */
            String getNumber();

            /**
             * <code>string number = 1;</code>
             */
            com.google.protobuf.ByteString
            getNumberBytes();
        }

        /**
         * Protobuf type {@code TestDto.PhoneNumber}
         */
        public static final class PhoneNumber extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:TestDto.PhoneNumber)
                PhoneNumberOrBuilder {
            private static final long serialVersionUID = 0L;

            // Use PhoneNumber.newBuilder() to construct.
            private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
            {
                super(builder);
            }

            private PhoneNumber()
            {
                number_ = "";
            }

            @Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields()
            {
                return this.unknownFields;
            }

            private PhoneNumber(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                this();
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                String s = input.readStringRequireUtf8();

                                number_ = s;
                                break;
                            }
                            default: {
                                if (!parseUnknownFieldProto3(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return TestDtoModel.internal_static_TestDto_PhoneNumber_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return TestDtoModel.internal_static_TestDto_PhoneNumber_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestDtoModel.TestDto.PhoneNumber.class, TestDtoModel.TestDto.PhoneNumber.Builder.class);
            }

            public static final int NUMBER_FIELD_NUMBER = 1;
            private volatile Object number_;

            /**
             * <code>string number = 1;</code>
             */
            public String getNumber()
            {
                Object ref = number_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    number_ = s;
                    return s;
                }
            }

            /**
             * <code>string number = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNumberBytes()
            {
                Object ref = number_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    number_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private byte memoizedIsInitialized = -1;

            @Override
            public final boolean isInitialized()
            {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException
            {
                if (!getNumberBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
                }
                unknownFields.writeTo(output);
            }

            @Override
            public int getSerializedSize()
            {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getNumberBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @Override
            public boolean equals(final Object obj)
            {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof TestDtoModel.TestDto.PhoneNumber)) {
                    return super.equals(obj);
                }
                TestDtoModel.TestDto.PhoneNumber other = (TestDtoModel.TestDto.PhoneNumber) obj;

                boolean result = true;
                result = result && getNumber()
                        .equals(other.getNumber());
                result = result && unknownFields.equals(other.unknownFields);
                return result;
            }

            @Override
            public int hashCode()
            {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + NUMBER_FIELD_NUMBER;
                hash = (53 * hash) + getNumber().hashCode();
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(java.io.InputStream input)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static TestDtoModel.TestDto.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @Override
            public Builder newBuilderForType()
            {
                return newBuilder();
            }

            public static Builder newBuilder()
            {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(TestDtoModel.TestDto.PhoneNumber prototype)
            {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @Override
            public Builder toBuilder()
            {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @Override
            protected Builder newBuilderForType(
                    BuilderParent parent)
            {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code TestDto.PhoneNumber}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:TestDto.PhoneNumber)
                    TestDtoModel.TestDto.PhoneNumberOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor()
                {
                    return TestDtoModel.internal_static_TestDto_PhoneNumber_descriptor;
                }

                @Override
                protected FieldAccessorTable
                internalGetFieldAccessorTable()
                {
                    return TestDtoModel.internal_static_TestDto_PhoneNumber_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    TestDtoModel.TestDto.PhoneNumber.class, TestDtoModel.TestDto.PhoneNumber.Builder.class);
                }

                // Construct using com.xk.nettydemo.bean.TestDtoModel.TestDto.PhoneNumber.newBuilder()
                private Builder()
                {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        BuilderParent parent)
                {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization()
                {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @Override
                public Builder clear()
                {
                    super.clear();
                    number_ = "";

                    return this;
                }

                @Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType()
                {
                    return TestDtoModel.internal_static_TestDto_PhoneNumber_descriptor;
                }

                @Override
                public TestDtoModel.TestDto.PhoneNumber getDefaultInstanceForType()
                {
                    return TestDtoModel.TestDto.PhoneNumber.getDefaultInstance();
                }

                @Override
                public TestDtoModel.TestDto.PhoneNumber build()
                {
                    TestDtoModel.TestDto.PhoneNumber result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @Override
                public TestDtoModel.TestDto.PhoneNumber buildPartial()
                {
                    TestDtoModel.TestDto.PhoneNumber result = new TestDtoModel.TestDto.PhoneNumber(this);
                    result.number_ = number_;
                    onBuilt();
                    return result;
                }

                @Override
                public Builder clone()
                {
                    return (Builder) super.clone();
                }

                @Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value)
                {
                    return (Builder) super.setField(field, value);
                }

                @Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field)
                {
                    return (Builder) super.clearField(field);
                }

                @Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof)
                {
                    return (Builder) super.clearOneof(oneof);
                }

                @Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, Object value)
                {
                    return (Builder) super.setRepeatedField(field, index, value);
                }

                @Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value)
                {
                    return (Builder) super.addRepeatedField(field, value);
                }

                @Override
                public Builder mergeFrom(com.google.protobuf.Message other)
                {
                    if (other instanceof TestDtoModel.TestDto.PhoneNumber) {
                        return mergeFrom((TestDtoModel.TestDto.PhoneNumber) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(TestDtoModel.TestDto.PhoneNumber other)
                {
                    if (other == TestDtoModel.TestDto.PhoneNumber.getDefaultInstance()) return this;
                    if (!other.getNumber().isEmpty()) {
                        number_ = other.number_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @Override
                public final boolean isInitialized()
                {
                    return true;
                }

                @Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException
                {
                    TestDtoModel.TestDto.PhoneNumber parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (TestDtoModel.TestDto.PhoneNumber) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private Object number_ = "";

                /**
                 * <code>string number = 1;</code>
                 */
                public String getNumber()
                {
                    Object ref = number_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        number_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>string number = 1;</code>
                 */
                public com.google.protobuf.ByteString
                getNumberBytes()
                {
                    Object ref = number_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (String) ref);
                        number_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string number = 1;</code>
                 */
                public Builder setNumber(
                        String value)
                {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    number_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string number = 1;</code>
                 */
                public Builder clearNumber()
                {

                    number_ = getDefaultInstance().getNumber();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string number = 1;</code>
                 */
                public Builder setNumberBytes(
                        com.google.protobuf.ByteString value)
                {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    number_ = value;
                    onChanged();
                    return this;
                }

                @Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields)
                {
                    return super.setUnknownFieldsProto3(unknownFields);
                }

                @Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields)
                {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:TestDto.PhoneNumber)
            }

            // @@protoc_insertion_point(class_scope:TestDto.PhoneNumber)
            private static final TestDtoModel.TestDto.PhoneNumber DEFAULT_INSTANCE;

            static {
                DEFAULT_INSTANCE = new TestDtoModel.TestDto.PhoneNumber();
            }

            public static TestDtoModel.TestDto.PhoneNumber getDefaultInstance()
            {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<PhoneNumber>
                    PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
                @Override
                public PhoneNumber parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException
                {
                    return new PhoneNumber(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<PhoneNumber> parser()
            {
                return PARSER;
            }

            @Override
            public com.google.protobuf.Parser<PhoneNumber> getParserForType()
            {
                return PARSER;
            }

            @Override
            public TestDtoModel.TestDto.PhoneNumber getDefaultInstanceForType()
            {
                return DEFAULT_INSTANCE;
            }

        }

        private int bitField0_;
        public static final int BOOLEAN_FIELD_NUMBER = 1;
        private boolean boolean_;

        /**
         * <code>bool boolean = 1;</code>
         */
        public boolean getBoolean()
        {
            return boolean_;
        }

        public static final int DOUB_FIELD_NUMBER = 2;
        private double doub_;

        /**
         * <code>double doub = 2;</code>
         */
        public double getDoub()
        {
            return doub_;
        }

        public static final int ID_FIELD_NUMBER = 3;
        private int id_;

        /**
         * <code>int32 id = 3;</code>
         */
        public int getId()
        {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 4;
        private volatile Object name_;

        /**
         * <code>string name = 4;</code>
         */
        public String getName()
        {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 4;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes()
        {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int B_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString b_;

        /**
         * <code>bytes b = 5;</code>
         */
        public com.google.protobuf.ByteString getB()
        {
            return b_;
        }

        public static final int PHONES_FIELD_NUMBER = 6;
        private java.util.List<PhoneNumber> phones_;

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        public java.util.List<PhoneNumber> getPhonesList()
        {
            return phones_;
        }

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        public java.util.List<? extends PhoneNumberOrBuilder>
        getPhonesOrBuilderList()
        {
            return phones_;
        }

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        public int getPhonesCount()
        {
            return phones_.size();
        }

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        public TestDtoModel.TestDto.PhoneNumber getPhones(int index)
        {
            return phones_.get(index);
        }

        /**
         * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
         */
        public TestDtoModel.TestDto.PhoneNumberOrBuilder getPhonesOrBuilder(
                int index)
        {
            return phones_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            if (boolean_ != false) {
                output.writeBool(1, boolean_);
            }
            if (doub_ != 0D) {
                output.writeDouble(2, doub_);
            }
            if (id_ != 0) {
                output.writeInt32(3, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
            }
            if (!b_.isEmpty()) {
                output.writeBytes(5, b_);
            }
            for (int i = 0; i < phones_.size(); i++) {
                output.writeMessage(6, phones_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize()
        {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (boolean_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, boolean_);
            }
            if (doub_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(2, doub_);
            }
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
            }
            if (!b_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, b_);
            }
            for (int i = 0; i < phones_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, phones_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj)
        {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestDtoModel.TestDto)) {
                return super.equals(obj);
            }
            TestDtoModel.TestDto other = (TestDtoModel.TestDto) obj;

            boolean result = true;
            result = result && (getBoolean()
                    == other.getBoolean());
            result = result && (
                    Double.doubleToLongBits(getDoub())
                            == Double.doubleToLongBits(
                            other.getDoub()));
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && getB()
                    .equals(other.getB());
            result = result && getPhonesList()
                    .equals(other.getPhonesList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode()
        {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getBoolean());
            hash = (37 * hash) + DOUB_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getDoub()));
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + B_FIELD_NUMBER;
            hash = (53 * hash) + getB().hashCode();
            if (getPhonesCount() > 0) {
                hash = (37 * hash) + PHONES_FIELD_NUMBER;
                hash = (53 * hash) + getPhonesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestDtoModel.TestDto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static TestDtoModel.TestDto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestDtoModel.TestDto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static TestDtoModel.TestDto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestDtoModel.TestDto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static TestDtoModel.TestDto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestDtoModel.TestDto parseFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestDtoModel.TestDto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestDtoModel.TestDto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestDtoModel.TestDto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestDtoModel.TestDto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestDtoModel.TestDto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder()
        {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestDtoModel.TestDto prototype)
        {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder()
        {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code TestDto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TestDto)
                TestDtoModel.TestDtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return TestDtoModel.internal_static_TestDto_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return TestDtoModel.internal_static_TestDto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestDtoModel.TestDto.class, TestDtoModel.TestDto.Builder.class);
            }

            // Construct using com.xk.nettydemo.bean.TestDtoModel.TestDto.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getPhonesFieldBuilder();
                }
            }

            @Override
            public Builder clear()
            {
                super.clear();
                boolean_ = false;

                doub_ = 0D;

                id_ = 0;

                name_ = "";

                b_ = com.google.protobuf.ByteString.EMPTY;

                if (phonesBuilder_ == null) {
                    phones_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                } else {
                    phonesBuilder_.clear();
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return TestDtoModel.internal_static_TestDto_descriptor;
            }

            @Override
            public TestDtoModel.TestDto getDefaultInstanceForType()
            {
                return TestDtoModel.TestDto.getDefaultInstance();
            }

            @Override
            public TestDtoModel.TestDto build()
            {
                TestDtoModel.TestDto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public TestDtoModel.TestDto buildPartial()
            {
                TestDtoModel.TestDto result = new TestDtoModel.TestDto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.boolean_ = boolean_;
                result.doub_ = doub_;
                result.id_ = id_;
                result.name_ = name_;
                result.b_ = b_;
                if (phonesBuilder_ == null) {
                    if (((bitField0_ & 0x00000020) == 0x00000020)) {
                        phones_ = java.util.Collections.unmodifiableList(phones_);
                        bitField0_ = (bitField0_ & ~0x00000020);
                    }
                    result.phones_ = phones_;
                } else {
                    result.phones_ = phonesBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone()
            {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field)
            {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof)
            {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value)
            {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof TestDtoModel.TestDto) {
                    return mergeFrom((TestDtoModel.TestDto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestDtoModel.TestDto other)
            {
                if (other == TestDtoModel.TestDto.getDefaultInstance()) return this;
                if (other.getBoolean() != false) {
                    setBoolean(other.getBoolean());
                }
                if (other.getDoub() != 0D) {
                    setDoub(other.getDoub());
                }
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getB() != com.google.protobuf.ByteString.EMPTY) {
                    setB(other.getB());
                }
                if (phonesBuilder_ == null) {
                    if (!other.phones_.isEmpty()) {
                        if (phones_.isEmpty()) {
                            phones_ = other.phones_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                        } else {
                            ensurePhonesIsMutable();
                            phones_.addAll(other.phones_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.phones_.isEmpty()) {
                        if (phonesBuilder_.isEmpty()) {
                            phonesBuilder_.dispose();
                            phonesBuilder_ = null;
                            phones_ = other.phones_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                            phonesBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getPhonesFieldBuilder() : null;
                        } else {
                            phonesBuilder_.addAllMessages(other.phones_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized()
            {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                TestDtoModel.TestDto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestDtoModel.TestDto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private boolean boolean_;

            /**
             * <code>bool boolean = 1;</code>
             */
            public boolean getBoolean()
            {
                return boolean_;
            }

            /**
             * <code>bool boolean = 1;</code>
             */
            public Builder setBoolean(boolean value)
            {

                boolean_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool boolean = 1;</code>
             */
            public Builder clearBoolean()
            {

                boolean_ = false;
                onChanged();
                return this;
            }

            private double doub_;

            /**
             * <code>double doub = 2;</code>
             */
            public double getDoub()
            {
                return doub_;
            }

            /**
             * <code>double doub = 2;</code>
             */
            public Builder setDoub(double value)
            {

                doub_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double doub = 2;</code>
             */
            public Builder clearDoub()
            {

                doub_ = 0D;
                onChanged();
                return this;
            }

            private int id_;

            /**
             * <code>int32 id = 3;</code>
             */
            public int getId()
            {
                return id_;
            }

            /**
             * <code>int32 id = 3;</code>
             */
            public Builder setId(int value)
            {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 id = 3;</code>
             */
            public Builder clearId()
            {

                id_ = 0;
                onChanged();
                return this;
            }

            private Object name_ = "";

            /**
             * <code>string name = 4;</code>
             */
            public String getName()
            {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string name = 4;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes()
            {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 4;</code>
             */
            public Builder setName(
                    String value)
            {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 4;</code>
             */
            public Builder clearName()
            {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 4;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString b_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes b = 5;</code>
             */
            public com.google.protobuf.ByteString getB()
            {
                return b_;
            }

            /**
             * <code>bytes b = 5;</code>
             */
            public Builder setB(com.google.protobuf.ByteString value)
            {
                if (value == null) {
                    throw new NullPointerException();
                }

                b_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes b = 5;</code>
             */
            public Builder clearB()
            {

                b_ = getDefaultInstance().getB();
                onChanged();
                return this;
            }

            private java.util.List<PhoneNumber> phones_ =
                    java.util.Collections.emptyList();

            private void ensurePhonesIsMutable()
            {
                if (!((bitField0_ & 0x00000020) == 0x00000020)) {
                    phones_ = new java.util.ArrayList<PhoneNumber>(phones_);
                    bitField0_ |= 0x00000020;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> phonesBuilder_;

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public java.util.List<PhoneNumber> getPhonesList()
            {
                if (phonesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(phones_);
                } else {
                    return phonesBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public int getPhonesCount()
            {
                if (phonesBuilder_ == null) {
                    return phones_.size();
                } else {
                    return phonesBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public TestDtoModel.TestDto.PhoneNumber getPhones(int index)
            {
                if (phonesBuilder_ == null) {
                    return phones_.get(index);
                } else {
                    return phonesBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder setPhones(
                    int index, TestDtoModel.TestDto.PhoneNumber value)
            {
                if (phonesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhonesIsMutable();
                    phones_.set(index, value);
                    onChanged();
                } else {
                    phonesBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder setPhones(
                    int index, TestDtoModel.TestDto.PhoneNumber.Builder builderForValue)
            {
                if (phonesBuilder_ == null) {
                    ensurePhonesIsMutable();
                    phones_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    phonesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder addPhones(TestDtoModel.TestDto.PhoneNumber value)
            {
                if (phonesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhonesIsMutable();
                    phones_.add(value);
                    onChanged();
                } else {
                    phonesBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder addPhones(
                    int index, TestDtoModel.TestDto.PhoneNumber value)
            {
                if (phonesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhonesIsMutable();
                    phones_.add(index, value);
                    onChanged();
                } else {
                    phonesBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder addPhones(
                    TestDtoModel.TestDto.PhoneNumber.Builder builderForValue)
            {
                if (phonesBuilder_ == null) {
                    ensurePhonesIsMutable();
                    phones_.add(builderForValue.build());
                    onChanged();
                } else {
                    phonesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder addPhones(
                    int index, TestDtoModel.TestDto.PhoneNumber.Builder builderForValue)
            {
                if (phonesBuilder_ == null) {
                    ensurePhonesIsMutable();
                    phones_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    phonesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder addAllPhones(
                    Iterable<? extends PhoneNumber> values)
            {
                if (phonesBuilder_ == null) {
                    ensurePhonesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, phones_);
                    onChanged();
                } else {
                    phonesBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder clearPhones()
            {
                if (phonesBuilder_ == null) {
                    phones_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                    onChanged();
                } else {
                    phonesBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public Builder removePhones(int index)
            {
                if (phonesBuilder_ == null) {
                    ensurePhonesIsMutable();
                    phones_.remove(index);
                    onChanged();
                } else {
                    phonesBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public TestDtoModel.TestDto.PhoneNumber.Builder getPhonesBuilder(
                    int index)
            {
                return getPhonesFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public TestDtoModel.TestDto.PhoneNumberOrBuilder getPhonesOrBuilder(
                    int index)
            {
                if (phonesBuilder_ == null) {
                    return phones_.get(index);
                } else {
                    return phonesBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public java.util.List<? extends PhoneNumberOrBuilder>
            getPhonesOrBuilderList()
            {
                if (phonesBuilder_ != null) {
                    return phonesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(phones_);
                }
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public TestDtoModel.TestDto.PhoneNumber.Builder addPhonesBuilder()
            {
                return getPhonesFieldBuilder().addBuilder(
                        TestDtoModel.TestDto.PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public TestDtoModel.TestDto.PhoneNumber.Builder addPhonesBuilder(
                    int index)
            {
                return getPhonesFieldBuilder().addBuilder(
                        index, TestDtoModel.TestDto.PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .TestDto.PhoneNumber phones = 6;</code>
             */
            public java.util.List<PhoneNumber.Builder>
            getPhonesBuilderList()
            {
                return getPhonesFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>
            getPhonesFieldBuilder()
            {
                if (phonesBuilder_ == null) {
                    phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>(
                            phones_,
                            ((bitField0_ & 0x00000020) == 0x00000020),
                            getParentForChildren(),
                            isClean());
                    phones_ = null;
                }
                return phonesBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:TestDto)
        }

        // @@protoc_insertion_point(class_scope:TestDto)
        private static final TestDtoModel.TestDto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestDtoModel.TestDto();
        }

        public static TestDtoModel.TestDto getDefaultInstance()
        {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TestDto>
                PARSER = new com.google.protobuf.AbstractParser<TestDto>() {
            @Override
            public TestDto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return new TestDto(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TestDto> parser()
        {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TestDto> getParserForType()
        {
            return PARSER;
        }

        @Override
        public TestDtoModel.TestDto getDefaultInstanceForType()
        {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TestDto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TestDto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TestDto_PhoneNumber_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TestDto_PhoneNumber_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor()
    {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rTestDto.proto\"\277\001\n\007TestDto\022\017\n\007boolean\030\001" +
                        " \001(\010\022\014\n\004doub\030\002 \001(\001\022\n\n\002id\030\003 \001(\005\022\014\n\004name\030\004" +
                        " \001(\t\022\t\n\001b\030\005 \001(\014\022$\n\006phones\030\006 \003(\0132\024.TestDt" +
                        "o.PhoneNumber\032\035\n\013PhoneNumber\022\016\n\006number\030\001" +
                        " \001(\t\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022" +
                        "\010\n\004WORK\020\002B%\n\025com.xk.nettydemo.beanB\014Test" +
                        "DtoModelb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root)
                    {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_TestDto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TestDto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TestDto_descriptor,
                new String[]{"Boolean", "Doub", "Id", "Name", "B", "Phones",});
        internal_static_TestDto_PhoneNumber_descriptor =
                internal_static_TestDto_descriptor.getNestedTypes().get(0);
        internal_static_TestDto_PhoneNumber_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TestDto_PhoneNumber_descriptor,
                new String[]{"Number",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
